apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: kured
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kured
    version: 1.5.0
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.3.0
